# Data Gathering and Cleaning

In [194]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [195]:
df = pd.read_csv('movies_metadata.csv')

In [196]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [197]:
df.columns
## Columns are used to check whoch movie recommendation system should i use . Like how should i segregate the data while making a model

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [199]:
df.shape

(45466, 24)

In [200]:
df.isnull().sum() 
## To check how many null values are there in each column

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [201]:
df = df.drop_duplicates().reset_index(drop=True)
## Used to delete all duplicate values and reset the indexes 
## .reset_index(drop=True) resets the index of a DataFrame back to the default integers (0, 1, 2, 3...) and completely deletes the old index.
## Without drop=True: pandas will make a new sequential index (0, 1, 2...), but it will keep your old index numbers and turn them into a regular data column named index.
## With drop=True: pandas deletes the old scrambled index entirely and replaces it with a clean, consecutive list of numbers starting at 0.

In [202]:
df.duplicated().sum()

np.int64(0)

In [203]:
df = df[['title','overview','genres','tagline','vote_average','vote_count','popularity']]

In [204]:
df

,title,overview,genres,tagline,vote_average,vote_count,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,5415.0,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,2413.0,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,34.0,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519
...,...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,1.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,3.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,6.0,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.0,0.163015

In [205]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
vote_count          6
popularity          5
dtype: int64

In [206]:
df = df.dropna(subset=['title'])
## removes any rows from your DataFrame where the title column has a missing, blank, or NaN (Not a Number) value
## If you are building a content-based or popularity model, a movie without a title is completely useless.

In [207]:
df['overview'] = df['overview'].fillna('')
## replaces every missing or NaN value in the overview column with an empty string ('').
## For overview, you use fillna('') because a movie might still have a valid title, genre, and budget, but simply lacks a plot summary. By replacing NaN with '', you keep the movie in your dataset while giving the text vectorizer a harmless, neutral blank space to read.

In [208]:
df.iloc[0]['genres']
##iloc stands for "integer location." It is a property used to select specific rows and columns from your DataFrame

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [209]:
df

,title,overview,genres,tagline,vote_average,vote_count,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,5415.0,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,2413.0,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,34.0,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519
...,...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,1.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,3.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,6.0,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.0,0.163015

In [210]:
import ast
df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

 What ast.literal_eval does it evaluates that string and safely converts it into an actual, usable Python list of dictionaries.
 
 [i['name'] for i in ...] It loops through each dictionary (i) inside your newly converted list and grabs only the value attached to the key 'name'.
 
 " ".join(...)This takes your clean list of genre strings and glues them together into a single string, using a space " " as the separator.
 
 .apply(lambda x: ...) function tells pandas to run this entire extraction process on every single row (x) down the genres column, overwriting the old messy text with the new clean text.

In [211]:
df.head()

,title,overview,genres,tagline,vote_average,vote_count,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,5415.0,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,34.0,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519

In [212]:
df['tagline'] = df['tagline'].fillna('')

In [213]:
df

,title,overview,genres,tagline,vote_average,vote_count,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,5415.0,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,34.0,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519
...,...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,Drama Family,Rising and falling between a man and woman,4.0,1.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,Drama,,9.0,3.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...",Action Drama Thriller,A deadly game of wits.,3.8,6.0,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",,,0.0,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,,,0.0,0.0,0.163015

In [214]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
vote_count      0
popularity      0
dtype: int64

In [251]:
df['tags'] =  (
    df['title'] + ' ' +
    df['overview'] + ' ' +
    df['genres']
)

In [252]:
df.head()

,title,overview,genres,tagline,vote_average,vote_count,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,5415.0,21.946943,"Toy Story Led by Woody, Andy's toys live happi..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,2413.0,17.015539,Jumanji When siblings Judy and Peter discover ...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,92.0,11.7129,Grumpier Old Men A family wedding reignites th...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,34.0,3.859495,"Waiting to Exhale Cheated on, mistreated and s..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,173.0,8.387519,Father of the Bride Part II Just when George B...

# NLP Text Processing

In [253]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

nltk -> The parent library that provides all human-language processing tools.
stopwords -> Drops useless filler words like "the", "and", and "is".
WordNetLemmatizer -> Flattens words to their base dictionary roots like converting "running" to "run".
re ->  Strips out annoying punctuation, symbols, and numbers using pattern matching.

In [254]:
nltk.download('stopwords')
nltk.download('wordnet')
# nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/prakharj/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/prakharj/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [255]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [256]:
def preprocess_text(text):
    #lowercase
    text = str(text).lower()
    #removed the punctuations
    text = re.sub('[^\w\s]|\d|_', ' ', text)
    # Split text into individual words
    words = text.split()
    
    # Remove stop words AND lemmatise the remaining words
    words = [lemmatizer.lemmatize(word) for word in words if word not in stop_words]

    # Glue the cleaned words back into a single clean string
    return " ".join(words)

In [257]:
df['tags']= df['tags'].apply(preprocess_text)

In [258]:
df['tags'][1]

'jumanji sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult trapped inside game year living room alan hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family'

# Text Vectorization

In [259]:
df = df.reset_index(drop=True)

In [260]:
indices = pd.Series(df.index,index=df['title']).drop_duplicates()

In [261]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [262]:
## TFIDF Vectorization evaluates how important a word is to a document within a collection or corpus [1]. It is calculated by multiplying two metrics

In [263]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000,ngram_range=(1, 2),stop_words = 'english')

In [264]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [265]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1126417 stored elements and shape (45447, 5000)>

In [266]:
from sklearn.metrics.pairwise import cosine_similarity

In [273]:
def recommend(title, n = 10):
    if title not in indices:
        return ['Movie not found']


    idx = indices[title]
    if isinstance(idx, pd.Series):
        idx = idx.iloc[0]
        
    sim_score = cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[::-1][1:n+1]

    return df['title'].iloc[similar_idx].tolist()
    # for i in similar_idx:
    #     print(df.iloc[i]['title'], sim_score[i])

In [276]:
recommend('Avatar',5)

['Avatar 2',
 'Thor: Ragnarok',
 'A Trip to the Moon',
 'Almighty Thor',
 "Frank Herbert's Dune"]

In [277]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))